#pragma once
#include <windows.h>
#include <d3d12.h>

// Forward declarations for DXR-related types missing from older headers.
#ifndef RTXBLOCKS_D3D12_MISC_TYPES
#define RTXBLOCKS_D3D12_MISC_TYPES
struct ID3D12MetaCommand;
enum D3D12_META_COMMAND_PARAMETER_TYPE {
    D3D12_META_COMMAND_PARAMETER_TYPE_FLOAT = 0
};
typedef UINT64 D3D12_GRAPHICS_STATES;
struct D3D12_RENDER_PASS_BEGINNING_ACCESS {
    UINT Placeholder;
};
struct D3D12_RENDER_PASS_ENDING_ACCESS {
    UINT Placeholder;
};
struct D3D12_RENDER_PASS_RENDER_TARGET_DESC {
    D3D12_CPU_DESCRIPTOR_HANDLE cpuDescriptor;
    D3D12_RENDER_PASS_BEGINNING_ACCESS BeginningAccess;
    D3D12_RENDER_PASS_ENDING_ACCESS EndingAccess;
};
struct D3D12_RENDER_PASS_DEPTH_STENCIL_DESC {
    D3D12_CPU_DESCRIPTOR_HANDLE cpuDescriptor;
    D3D12_RENDER_PASS_BEGINNING_ACCESS DepthBeginningAccess;
    D3D12_RENDER_PASS_BEGINNING_ACCESS StencilBeginningAccess;
    D3D12_RENDER_PASS_ENDING_ACCESS DepthEndingAccess;
    D3D12_RENDER_PASS_ENDING_ACCESS StencilEndingAccess;
};
enum D3D12_RENDER_PASS_FLAGS {
    D3D12_RENDER_PASS_FLAG_NONE = 0
};
#endif

#ifndef RTXBLOCKS_D3D12_META_COMMAND_TYPES
#define RTXBLOCKS_D3D12_META_COMMAND_TYPES
enum D3D12_META_COMMAND_PARAMETER_STAGE {
    D3D12_META_COMMAND_PARAMETER_STAGE_CREATION = 0
};
struct D3D12_META_COMMAND_PARAMETER_DESC {
    const WCHAR* Name;
    D3D12_META_COMMAND_PARAMETER_TYPE Type;
    D3D12_META_COMMAND_PARAMETER_STAGE Stage;
    UINT64 Offset;
    UINT64 Size;
};
struct D3D12_META_COMMAND_DESC {
    GUID Id;
    const WCHAR* Name;
    D3D12_GRAPHICS_STATES StateDependency;
    D3D12_META_COMMAND_PARAMETER_DESC* pParameters;
    UINT ParameterCount;
};
#endif

#ifndef RTXBLOCKS_D3D12_SERIALIZED_DATA_TYPES
#define RTXBLOCKS_D3D12_SERIALIZED_DATA_TYPES
enum D3D12_SERIALIZED_DATA_TYPE {
    D3D12_SERIALIZED_DATA_RAYTRACING_ACCELERATION_STRUCTURE = 0
};
struct D3D12_SERIALIZED_DATA_DRIVER_MATCHING_IDENTIFIER {
    UINT DriverOpaqueGUID[4];
    UINT DriverOpaqueVersion[2];
};
enum D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS {
    D3D12_DRIVER_MATCHING_IDENTIFIER_COMPATIBLE = 0,
    D3D12_DRIVER_MATCHING_IDENTIFIER_UNSUPPORTED = 1,
    D3D12_DRIVER_MATCHING_IDENTIFIER_INCOMPATIBLE_VERSION = 2
};
#endif

#ifndef RTXBLOCKS_D3D12_RT_POSTBUILD
#define RTXBLOCKS_D3D12_RT_POSTBUILD
enum D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_TYPE {
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_COMPACTED_SIZE = 0,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_TOOLS_VISUALIZATION = 1,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_SERIALIZATION = 2,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_CURRENT_SIZE = 3
};
struct D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC {
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_TYPE InfoType;
    D3D12_GPU_VIRTUAL_ADDRESS DestBuffer;
};
enum D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE {
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE_CLONE = 0,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE_COMPACT = 1,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE_VISUALIZATION_DECODE_FOR_TOOLS = 2,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE_SERIALIZE = 3,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE_DESERIALIZE = 4
};
#endif

// Minimal DXR declarations for MinGW headers that lack DXR types.
#ifndef D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT
#define D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT 32
#endif
#ifndef D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES
#define D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES 32
#endif

#ifndef D3D12_RAYTRACING_GEOMETRY_FLAG_OPAQUE
typedef enum D3D12_RAYTRACING_GEOMETRY_FLAGS {
    D3D12_RAYTRACING_GEOMETRY_FLAG_NONE = 0,
    D3D12_RAYTRACING_GEOMETRY_FLAG_OPAQUE = 0x1,
    D3D12_RAYTRACING_GEOMETRY_FLAG_NO_DUPLICATE_ANYHIT_INVOCATION = 0x2
} D3D12_RAYTRACING_GEOMETRY_FLAGS;
#endif

#ifndef D3D12_RAYTRACING_GEOMETRY_TYPE_TRIANGLES
typedef enum D3D12_RAYTRACING_GEOMETRY_TYPE {
    D3D12_RAYTRACING_GEOMETRY_TYPE_TRIANGLES = 0,
    D3D12_RAYTRACING_GEOMETRY_TYPE_PROCEDURAL_PRIMITIVE_AABBS = 1
} D3D12_RAYTRACING_GEOMETRY_TYPE;
#endif

#ifndef D3D12_RAYTRACING_GEOMETRY_DESC
typedef struct D3D12_GPU_VIRTUAL_ADDRESS_AND_STRIDE {
    D3D12_GPU_VIRTUAL_ADDRESS StartAddress;
    UINT StrideInBytes;
} D3D12_GPU_VIRTUAL_ADDRESS_AND_STRIDE;

typedef struct D3D12_RAYTRACING_GEOMETRY_TRIANGLES_DESC {
    D3D12_GPU_VIRTUAL_ADDRESS_AND_STRIDE VertexBuffer;
    DXGI_FORMAT VertexFormat;
    UINT VertexCount;
    D3D12_GPU_VIRTUAL_ADDRESS IndexBuffer;
    UINT IndexCount;
    DXGI_FORMAT IndexFormat;
    D3D12_GPU_VIRTUAL_ADDRESS Transform3x4;
} D3D12_RAYTRACING_GEOMETRY_TRIANGLES_DESC;

typedef struct D3D12_RAYTRACING_GEOMETRY_DESC {
    D3D12_RAYTRACING_GEOMETRY_TYPE Type;
    D3D12_RAYTRACING_GEOMETRY_FLAGS Flags;
    union {
        D3D12_RAYTRACING_GEOMETRY_TRIANGLES_DESC Triangles;
    };
} D3D12_RAYTRACING_GEOMETRY_DESC;
#endif

#ifndef D3D12_RAYTRACING_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL
typedef enum D3D12_RAYTRACING_ACCELERATION_STRUCTURE_TYPE {
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL = 0,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL = 1
} D3D12_RAYTRACING_ACCELERATION_STRUCTURE_TYPE;
#endif

#ifndef D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_TRACE
typedef enum D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS {
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_NONE = 0,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_ALLOW_UPDATE = 0x1,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_ALLOW_COMPACTION = 0x2,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_TRACE = 0x4,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_BUILD = 0x8,
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_MINIMIZE_MEMORY = 0x10
} D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS;
#endif

#ifndef D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE
#define D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE static_cast<D3D12_RESOURCE_STATES>(0x400000)
#endif

#ifndef D3D12_ELEMENTS_LAYOUT_ARRAY
typedef enum D3D12_ELEMENTS_LAYOUT {
    D3D12_ELEMENTS_LAYOUT_ARRAY = 0,
    D3D12_ELEMENTS_LAYOUT_ARRAY_OF_POINTERS = 1
} D3D12_ELEMENTS_LAYOUT;
#endif

#ifndef D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_TRACE
#define D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_TRACE D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_TRACE
#endif

#ifndef D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS
typedef struct D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS {
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_TYPE Type;
    D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS Flags;
    UINT NumDescs;
    D3D12_ELEMENTS_LAYOUT DescsLayout;
    union {
        const D3D12_RAYTRACING_GEOMETRY_DESC* pGeometryDescs;
        D3D12_GPU_VIRTUAL_ADDRESS InstanceDescs;
    };
} D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS;
#endif

#ifndef D3D12_RAYTRACING_ACCELERATION_STRUCTURE_PREBUILD_INFO
typedef struct D3D12_RAYTRACING_ACCELERATION_STRUCTURE_PREBUILD_INFO {
    UINT64 ResultDataMaxSizeInBytes;
    UINT64 ScratchDataSizeInBytes;
    UINT64 UpdateScratchDataSizeInBytes;
} D3D12_RAYTRACING_ACCELERATION_STRUCTURE_PREBUILD_INFO;
#endif

#ifndef D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC
typedef struct D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC {
    D3D12_GPU_VIRTUAL_ADDRESS DestAccelerationStructureData;
    D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS Inputs;
    D3D12_GPU_VIRTUAL_ADDRESS SourceAccelerationStructureData;
    D3D12_GPU_VIRTUAL_ADDRESS ScratchAccelerationStructureData;
} D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC;
#endif

#ifndef D3D12_RAYTRACING_INSTANCE_DESC
typedef struct D3D12_RAYTRACING_INSTANCE_DESC {
    float Transform[3][4];
    UINT InstanceID : 24;
    UINT InstanceMask : 8;
    UINT InstanceContributionToHitGroupIndex : 24;
    UINT Flags : 8;
    D3D12_GPU_VIRTUAL_ADDRESS AccelerationStructure;
} D3D12_RAYTRACING_INSTANCE_DESC;
#endif

#ifndef D3D12_STATE_OBJECT_TYPE_RAYTRACING_PIPELINE
typedef enum D3D12_STATE_OBJECT_TYPE {
    D3D12_STATE_OBJECT_TYPE_COLLECTION = 0,
    D3D12_STATE_OBJECT_TYPE_RAYTRACING_PIPELINE = 3
} D3D12_STATE_OBJECT_TYPE;
#endif

#ifndef D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY
typedef enum D3D12_STATE_SUBOBJECT_TYPE {
    D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY = 0,
    D3D12_STATE_SUBOBJECT_TYPE_EXISTING_COLLECTION = 1,
    D3D12_STATE_SUBOBJECT_TYPE_SUBOBJECT_TO_EXPORTS_ASSOCIATION = 2,
    D3D12_STATE_SUBOBJECT_TYPE_DXIL_SUBOBJECT_TO_EXPORTS_ASSOCIATION = 3,
    D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG = 5,
    D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG = 6,
    D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_ROOT_SIGNATURE = 7,
    D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE = 8,
    D3D12_STATE_SUBOBJECT_TYPE_HIT_GROUP = 11
} D3D12_STATE_SUBOBJECT_TYPE;
#endif

#ifndef D3D12_EXPORT_DESC
typedef enum D3D12_EXPORT_FLAGS {
    D3D12_EXPORT_FLAG_NONE = 0
} D3D12_EXPORT_FLAGS;

typedef struct D3D12_EXPORT_DESC {
    LPCWSTR Name;
    LPCWSTR ExportToRename;
    D3D12_EXPORT_FLAGS Flags;
} D3D12_EXPORT_DESC;
#endif

#ifndef D3D12_DXIL_LIBRARY_DESC
typedef struct D3D12_DXIL_LIBRARY_DESC {
    D3D12_SHADER_BYTECODE DXILLibrary;
    UINT NumExports;
    const D3D12_EXPORT_DESC* pExports;
} D3D12_DXIL_LIBRARY_DESC;
#endif

#ifndef D3D12_HIT_GROUP_DESC
typedef enum D3D12_HIT_GROUP_TYPE {
    D3D12_HIT_GROUP_TYPE_TRIANGLES = 0,
    D3D12_HIT_GROUP_TYPE_PROCEDURAL_PRIMITIVE = 1
} D3D12_HIT_GROUP_TYPE;

typedef struct D3D12_HIT_GROUP_DESC {
    LPCWSTR HitGroupExport;
    LPCWSTR AnyHitShaderImport;
    LPCWSTR ClosestHitShaderImport;
    LPCWSTR IntersectionShaderImport;
    D3D12_HIT_GROUP_TYPE Type;
} D3D12_HIT_GROUP_DESC;
#endif

#ifndef D3D12_RAYTRACING_SHADER_CONFIG
typedef struct D3D12_RAYTRACING_SHADER_CONFIG {
    UINT MaxPayloadSizeInBytes;
    UINT MaxAttributeSizeInBytes;
} D3D12_RAYTRACING_SHADER_CONFIG;
#endif

#ifndef D3D12_RAYTRACING_PIPELINE_CONFIG
typedef struct D3D12_RAYTRACING_PIPELINE_CONFIG {
    UINT MaxTraceRecursionDepth;
} D3D12_RAYTRACING_PIPELINE_CONFIG;
#endif

#ifndef D3D12_STATE_SUBOBJECT
typedef struct D3D12_STATE_SUBOBJECT {
    D3D12_STATE_SUBOBJECT_TYPE Type;
    const void* pDesc;
} D3D12_STATE_SUBOBJECT;
#endif

#ifndef D3D12_STATE_OBJECT_DESC
typedef struct D3D12_STATE_OBJECT_DESC {
    D3D12_STATE_OBJECT_TYPE Type;
    UINT NumSubobjects;
    const D3D12_STATE_SUBOBJECT* pSubobjects;
} D3D12_STATE_OBJECT_DESC;
#endif

#ifndef D3D12_DISPATCH_RAYS_DESC
typedef struct D3D12_GPU_VIRTUAL_ADDRESS_RANGE {
    D3D12_GPU_VIRTUAL_ADDRESS StartAddress;
    UINT64 SizeInBytes;
} D3D12_GPU_VIRTUAL_ADDRESS_RANGE;

typedef struct D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE {
    D3D12_GPU_VIRTUAL_ADDRESS StartAddress;
    UINT64 SizeInBytes;
    UINT64 StrideInBytes;
} D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE;

typedef struct D3D12_DISPATCH_RAYS_DESC {
    D3D12_GPU_VIRTUAL_ADDRESS_RANGE RayGenerationShaderRecord;
    D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE MissShaderTable;
    D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE HitGroupTable;
    D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE CallableShaderTable;
    UINT Width;
    UINT Height;
    UINT Depth;
} D3D12_DISPATCH_RAYS_DESC;
#endif

#ifndef D3D12_RAYTRACING_INSTANCE_FLAG_NONE
#define D3D12_RAYTRACING_INSTANCE_FLAG_NONE 0
#endif

#ifndef D3D12_SRV_DIMENSION_RAYTRACING_ACCELERATION_STRUCTURE
#define D3D12_SRV_DIMENSION_RAYTRACING_ACCELERATION_STRUCTURE static_cast<D3D12_SRV_DIMENSION>(11)
typedef struct D3D12_RAYTRACING_ACCELERATION_STRUCTURE_SRV {
    D3D12_GPU_VIRTUAL_ADDRESS Location;
} D3D12_RAYTRACING_ACCELERATION_STRUCTURE_SRV;

typedef struct D3D12_SHADER_RESOURCE_VIEW_DESC_RTX {
    DXGI_FORMAT Format;
    D3D12_SRV_DIMENSION ViewDimension;
    UINT Shader4ComponentMapping;
    __C89_NAMELESS union {
        D3D12_BUFFER_SRV Buffer;
        D3D12_TEX1D_SRV Texture1D;
        D3D12_TEX1D_ARRAY_SRV Texture1DArray;
        D3D12_TEX2D_SRV Texture2D;
        D3D12_TEX2D_ARRAY_SRV Texture2DArray;
        D3D12_TEX2DMS_SRV Texture2DMS;
        D3D12_TEX2DMS_ARRAY_SRV Texture2DMSArray;
        D3D12_TEX3D_SRV Texture3D;
        D3D12_TEXCUBE_SRV TextureCube;
        D3D12_TEXCUBE_ARRAY_SRV TextureCubeArray;
        D3D12_RAYTRACING_ACCELERATION_STRUCTURE_SRV RaytracingAccelerationStructure;
    } __C89_NAMELESSUNIONNAME;
} D3D12_SHADER_RESOURCE_VIEW_DESC_RTX;
#endif

struct __declspec(uuid("47016943-fca8-4594-93ea-af258b55346d")) ID3D12StateObject : public IUnknown {
};

struct __declspec(uuid("de5fa827-9bf9-4f26-89ff-d7f56fde3860")) ID3D12StateObjectProperties : public IUnknown {
    virtual void* GetShaderIdentifier(LPCWSTR pExportName) = 0;
    virtual UINT64 GetShaderStackSize(LPCWSTR pExportName) = 0;
    virtual UINT64 GetPipelineStackSize() = 0;
    virtual void SetPipelineStackSize(UINT64 PipelineStackSizeInBytes) = 0;
};

struct __declspec(uuid("8b4f173b-2fea-4b80-8f58-4307191ab95d")) ID3D12Device5 : public ID3D12Device {
    virtual HRESULT CreateLifetimeTracker(IUnknown*, REFIID, void**) = 0;
    virtual void RemoveDevice() = 0;
    virtual HRESULT EnumerateMetaCommands(UINT*, D3D12_META_COMMAND_DESC*) = 0;
    virtual HRESULT EnumerateMetaCommandParameters(GUID, D3D12_META_COMMAND_PARAMETER_STAGE, UINT*, D3D12_META_COMMAND_PARAMETER_DESC*) = 0;
    virtual HRESULT CreateMetaCommand(GUID, UINT, const void*, SIZE_T, REFIID, void**) = 0;
    virtual HRESULT CreateStateObject(const D3D12_STATE_OBJECT_DESC*, REFIID, void**) = 0;
    virtual void GetRaytracingAccelerationStructurePrebuildInfo(const D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS*,
                                                                 D3D12_RAYTRACING_ACCELERATION_STRUCTURE_PREBUILD_INFO*) = 0;
    virtual D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS CheckDriverMatchingIdentifier(D3D12_SERIALIZED_DATA_TYPE, const D3D12_SERIALIZED_DATA_DRIVER_MATCHING_IDENTIFIER*) = 0;
};

struct __declspec(uuid("8754318e-d3a9-4541-98cf-645b50dc4874")) ID3D12GraphicsCommandList4 : public ID3D12GraphicsCommandList {
    virtual void BeginRenderPass(UINT, const D3D12_RENDER_PASS_RENDER_TARGET_DESC*, const D3D12_RENDER_PASS_DEPTH_STENCIL_DESC*, D3D12_RENDER_PASS_FLAGS) = 0;
    virtual void EndRenderPass() = 0;
    virtual void InitializeMetaCommand(ID3D12MetaCommand*, const void*, SIZE_T) = 0;
    virtual void ExecuteMetaCommand(ID3D12MetaCommand*, const void*, SIZE_T) = 0;
    virtual void BuildRaytracingAccelerationStructure(const D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC*, UINT,
                                                      const D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC*) = 0;
    virtual void EmitRaytracingAccelerationStructurePostbuildInfo(const D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC*,
                                                                   UINT, const D3D12_GPU_VIRTUAL_ADDRESS*) = 0;
    virtual void CopyRaytracingAccelerationStructure(D3D12_GPU_VIRTUAL_ADDRESS, D3D12_GPU_VIRTUAL_ADDRESS,
                                                     D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE) = 0;
    virtual void SetPipelineState1(ID3D12StateObject*) = 0;
    virtual void DispatchRays(const D3D12_DISPATCH_RAYS_DESC*) = 0;
};
